import { z } from 'zod';
import { sweStepFactory } from './steps/swe.js';

export interface StepFactory {
  id: string;
  description: string;
  inputSchema: z.ZodType;
  outputSchema: z.ZodType;
  execute: (input: any, context: StepContext) => Promise<any>;
}

export interface StepContext {
  agentId: string;
  orgId: string;
  projectId: string;
  config: Record<string, any>;
}

const pmReviewInputSchema = z.object({
  taskTitle: z.string(),
  taskDescription: z.string().optional(),
});

const pmReviewOutputSchema = z.object({
  isReady: z.boolean(),
  acceptanceCriteria: z.array(z.string()),
  feedback: z.string().optional(),
});

const architectInputSchema = z.object({
  taskTitle: z.string(),
  acceptanceCriteria: z.array(z.string()),
  projectContext: z.string().optional(),
});

const architectOutputSchema = z.object({
  plan: z.string(),
  filesToChange: z.array(z.string()),
  estimatedComplexity: z.enum(['low', 'medium', 'high']),
});

const reviewInputSchema = z.object({
  filesChanged: z.array(z.string()),
  diff: z.string().optional(),
});

const reviewOutputSchema = z.object({
  verdict: z.enum(['approve', 'request_changes', 'reject']),
  comments: z.array(z.object({
    file: z.string(),
    line: z.number().optional(),
    body: z.string(),
  })),
  summary: z.string(),
});

const reportInputSchema = z.object({
  taskId: z.string(),
  verdict: z.string().optional(),
  summary: z.string().optional(),
});

const reportOutputSchema = z.object({
  reportWritten: z.boolean(),
  taskStatusUpdated: z.boolean(),
  finalStatus: z.string(),
});

const stepFactories: Record<string, () => StepFactory> = {
  'pm-review': () => ({
    id: 'pm-review',
    description: 'Reviews task clarity and outputs acceptance criteria',
    inputSchema: pmReviewInputSchema,
    outputSchema: pmReviewOutputSchema,
    execute: async (input, context) => {
      return {
        isReady: true,
        acceptanceCriteria: ['Criteria generated by PM review agent'],
        feedback: `Task "${input.taskTitle}" reviewed`,
      };
    },
  }),

  'architect': () => ({
    id: 'architect',
    description: 'Designs an implementation plan',
    inputSchema: architectInputSchema,
    outputSchema: architectOutputSchema,
    execute: async (input, context) => {
      return {
        plan: `Implementation plan for: ${input.taskTitle}`,
        filesToChange: [],
        estimatedComplexity: 'medium' as const,
      };
    },
  }),

  'swe': sweStepFactory,

  'review': () => ({
    id: 'review',
    description: 'Reviews code diff and outputs verdict',
    inputSchema: reviewInputSchema,
    outputSchema: reviewOutputSchema,
    execute: async (input, context) => {
      return {
        verdict: 'approve' as const,
        comments: [],
        summary: `Reviewed ${input.filesChanged.length} files`,
      };
    },
  }),

  'report': () => ({
    id: 'report',
    description: 'Writes summary and updates task status',
    inputSchema: reportInputSchema,
    outputSchema: reportOutputSchema,
    execute: async (input, context) => {
      return {
        reportWritten: true,
        taskStatusUpdated: true,
        finalStatus: input.verdict === 'approve' ? 'done' : 'in_review',
      };
    },
  }),
};

export function getStepFactory(stepType: string): StepFactory {
  const factory = stepFactories[stepType];
  if (!factory) {
    throw new Error(`Unknown step type: ${stepType}`);
  }
  return factory();
}

export function getAvailableStepTypes(): string[] {
  return Object.keys(stepFactories);
}
